version = "3.7.2"
runner.dialect = scala3
preset = default
assumeStandardLibraryStripMargin = true
maxColumn = 130
align.preset = more
align.allowOverflow = true
comments.wrap = no
docstrings.wrap = no
