apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: dt-demo
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318

      syslog:
        udp:
          listen_address: "0.0.0.0:1514"
        protocol: rfc5424

      prometheus:
        config:
          scrape_configs:
            - job_name: dt-metrics-demo
              scrape_interval: 15s
              static_configs:
                - targets: ["dt-metrics-demo.dt-demo.svc.cluster.local:8080"]

    processors:
      batch:

    exporters:
      otlphttp/dynatrace:
        endpoint: "https://wun8183h.sprint.dynatracelabs.com/api/v2/otlp"
        headers:
          Authorization: "Api-Token ${env:DT_API_TOKEN}"

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [otlphttp/dynatrace]
        logs:
          receivers: [otlp, syslog]
          processors: [batch]
          exporters: [otlphttp/dynatrace]
